version: '3.7'
services:

  ps_postgresql:
    image: postgres:11.4
    networks:
      ps_net:
        aliases:
          - postgres
    container_name: ps-postgresql
    restart: always
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data/
      - ./docker/postgresql/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  ps_nginx:
    image: nginx:1.16.0
    restart: always
    container_name: ps-nginx
    networks:
      ps_net:
        aliases:
          - nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docs/swagger.yml:/etc/nginx/html/swagger.yml
      - ./docker/nginx/html/index.html:/etc/nginx/html/index.html

  ps_instance1:
    build:
      context: .
      dockerfile: docker/payment-system/Dockerfile
    image: payment-system:1.0.0
    restart: always
    container_name: ps-instance1
    networks:
      ps_net:
        aliases:
          - instance1
    healthcheck:
      test: curl -f http://localhost:$$HTTP_PORT/v1/healthcheck
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - ${INSTANCE1_PORT}:${HTTP_PORT}
    volumes:
      - ./:/mnt

  ps_instance2:
    build:
      context: .
      dockerfile: docker/payment-system/Dockerfile
    image: payment-system:1.0.0
    restart: always
    container_name: ps-instance2
    networks:
      ps_net:
        aliases:
          - instance2
    healthcheck:
      test: curl -f http://localhost:$$HTTP_PORT/v1/healthcheck
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - ${INSTANCE2_PORT}:${HTTP_PORT}
    volumes:
      - ./:/mnt

networks:
  ps_net:
    driver: bridge
